/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EvelinImport } from './routes/evelin'
import { Route as BarnaImport } from './routes/barna'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const EvelinRoute = EvelinImport.update({
  path: '/evelin',
  getParentRoute: () => rootRoute,
} as any)

const BarnaRoute = BarnaImport.update({
  path: '/barna',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/barna': {
      id: '/barna'
      path: '/barna'
      fullPath: '/barna'
      preLoaderRoute: typeof BarnaImport
      parentRoute: typeof rootRoute
    }
    '/evelin': {
      id: '/evelin'
      path: '/evelin'
      fullPath: '/evelin'
      preLoaderRoute: typeof EvelinImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  BarnaRoute,
  EvelinRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/barna",
        "/evelin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/barna": {
      "filePath": "barna.tsx"
    },
    "/evelin": {
      "filePath": "evelin.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
